apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-view
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  namespace: prometheus
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: pods-viewer # ClusterRole name
  apiGroup: rbac.authorization.k8s.io