apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-admin
subjects:
- kind: ServiceAccount
  name: bob # name of your service account
  namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: admin # ClusterRole name
  apiGroup: rbac.authorization.k8s.io