apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: server
        image: dibilder/paymentservice:4.0
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
