apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: dibilder/paymentservice:3.0
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
