apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
    name: web # Название Pod
    labels: # Метки в формате key: value
        key: value
spec: # Описание Pod
    containers: # Описание контейнеров внутри Pod
    - name: web # Название контейнера
      image: dibilder/nginxfiles:1.0 # Образ из которого создается контейнер
      volumeMounts:
      - name: app
        mountPath: /app
    initContainers:
    - name: init-myservice
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app
    volumes:
    - name: app
      emptyDir: {}